version: '3.2'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: ./api/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./api:/api
  #   environment:
  #     - PORT:8080
  #   ports:
  #     - 127.0.0.1:5000:5000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - ./frontend/.env
    volumes:
      - ./frontend:/app
    environment:
      - PORT:3000
    ports:
      - 127.0.0.1:5000:5000
